replicaCount: 1

image:
  repository: ghcr.io/adamoctoclose/sample.frontend
  tag: 25.1.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

service:
  type: ClusterIP
  port: 81